import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Layouts/Navbar.jsx";
import { CartProvider } from "@/context/CartContext.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <CartProvider>
          <Navbar />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}

